### ISSUE TITLE
Altars don't lure mobs

### ISSUE THREAD

**Issue by QuasiStellar** [nojus297/pixel-dungeon-gdx#1]
Sacrificial altars or however they are called are supposed to notify mobs about hero's position, this doesn't work in this version.

Altars also accept sacrifice only if the mob you're killing has the altar buff. It's supposed to work even if only hero has the buff.

**Comment by gnojus** [comment]
This is a new feature in Pixel Dungeon 1.9.2, should work with the newest release (https://github.com/nojus297/pixel-dungeon-gdx/releases/).

**Comment by QuasiStellar** [comment]
Nice!
